package com.example.myapplication.domain

import com.example.myapplication.data.model.EchoForeshadow
import com.example.myapplication.data.model.ForeshadowSourceRef
import com.example.myapplication.data.model.ForeshadowState
import com.example.myapplication.data.model.ForeshadowOutcome
import com.example.myapplication.data.model.LifeRecord
import com.example.myapplication.data.repository.ForeshadowRepository
import com.example.myapplication.policy.ForeshadowPolicy
import java.util.UUID

/** Coordinates source evidence with the persistent foreshadow collection. */
class ForeshadowCoordinator(
    private val repository: ForeshadowRepository = ForeshadowRepository(),
    private val interpreter: ForeshadowInterpreter? = null
) {
    suspend fun backfill(records: List<LifeRecord>): Int {
        val known = repository.getAll().toMutableList()
        var createdCount = 0
        records.sortedBy { it.createdAt }.forEach { record ->
            if (record.source == "foreshadow_checkin") return@forEach
            val source = record.toSourceRef()
            val watching = known.filter { it.state == ForeshadowState.WATCHING }
            ForeshadowPolicy.findRelated(record.content, watching)
                ?.takeIf { thread -> thread.sourceRefs.none { it.id == record.id } }
                ?.let { related ->
                    repository.addEvidence(related.id, source)
                    val index = known.indexOfFirst { it.id == related.id }
                    if (index >= 0) {
                        known[index] = related.copy(
                            sourceRefs = related.sourceRefs + source,
                            lastEvidenceAt = maxOf(related.lastEvidenceAt, source.createdAt)
                        )
                    }
                }

            val candidate = ForeshadowPolicy.detect(record.content, record.createdAt)
                ?: return@forEach
            if (ForeshadowPolicy.isDuplicate(
                    candidate.subject,
                    known.filter { it.state != ForeshadowState.DISMISSED }
                )) return@forEach

            val thread = candidate.toThread(record, source)
            repository.add(thread)
            known += thread
            createdCount += 1
        }
        return createdCount
    }

    suspend fun onRecordSaved(record: LifeRecord): EchoForeshadow? {
        // A response generated by this feature is already linked explicitly.
        if (record.source == "foreshadow_checkin") return null

        val source = record.toSourceRef()
        val watching = repository.getWatching()

        ForeshadowPolicy.findRelated(record.content, watching)
            ?.takeIf { thread -> thread.sourceRefs.none { it.id == record.id } }
            ?.let { related ->
                val interpretation = try {
                    interpreter?.interpretRelation(related, record.content)
                } catch (_: Exception) {
                    null
                }
                if (interpretation == null || interpretation.matches) {
                    repository.addEvidence(
                        threadId = related.id,
                        source = source,
                        suggestedOutcome = interpretation?.relation?.toOutcome(),
                        suggestionConfidence = interpretation?.confidence
                    )
                }
            }

        val localCandidate = ForeshadowPolicy.detect(record.content, record.createdAt) ?: return null
        val allActive = repository.getAll().filter { it.state != ForeshadowState.DISMISSED }
        if (ForeshadowPolicy.isDuplicate(localCandidate.subject, allActive)) return null

        val decision = try {
            interpreter?.interpretCandidate(record.content, record.createdAt, localCandidate)
        } catch (_: Exception) {
            null
        }
        if (decision?.qualifies == false) return null
        val candidate = decision?.candidate ?: localCandidate
        if (ForeshadowPolicy.isDuplicate(candidate.subject, allActive)) return null

        val thread = candidate.toThread(record, source)
        repository.add(thread)
        return thread
    }

    private fun ForeshadowPolicy.Candidate.toThread(
        record: LifeRecord,
        source: ForeshadowSourceRef
    ) = EchoForeshadow(
        id = UUID.randomUUID().toString(),
        subject = subject,
        title = title,
        followUpQuestion = followUpQuestion,
        confidence = confidence,
        importance = record.importance.coerceIn(1, 5),
        sourceRefs = listOf(source),
        createdAt = record.createdAt,
        lastEvidenceAt = record.createdAt,
        nextCheckAt = nextCheckAt
    )

    private fun LifeRecord.toSourceRef() = ForeshadowSourceRef(
        type = "life_record",
        id = id,
        excerpt = content.take(180),
        createdAt = createdAt
    )

    private fun ForeshadowInterpreter.Relation.toOutcome(): ForeshadowOutcome? = when (this) {
        ForeshadowInterpreter.Relation.RESOLVED -> ForeshadowOutcome.HAPPENED
        ForeshadowInterpreter.Relation.CHANGED -> ForeshadowOutcome.CHANGED
        ForeshadowInterpreter.Relation.ABANDONED -> ForeshadowOutcome.ABANDONED
        ForeshadowInterpreter.Relation.PROGRESS,
        ForeshadowInterpreter.Relation.CONTINUING -> ForeshadowOutcome.CONTINUING
        ForeshadowInterpreter.Relation.NO_MATCH -> null
    }
}
